### ISSUE TITLE
0.1.6 Huge delays to retrieve state

### ISSUE THREAD

**Issue by dannyyy** [StyraHem/ShellyForHASS#185]
Since I updated today, I have huge delays between the point in time when I trigger a command/action and the time it gets reflected within home-assistant.

Pressing power-on and the light is immediately lighted. But within home-assistant, the state changes to on for 0.5-1s and after that it shows again the initial state. After another 5-30s the actual state will be displayed. An as long as the actual state is wrong I cannot switch again. Despite I enable `assumed_state: true`, then I get two toggles. But even then, the state indication is as wrong as described before.

This behaviour is always reproducible for the following devices and intentions:
- Shelly 1 to switch a light
- Shelly 1PM to switch a socket
- Shelly 2.5 to control a roller shutter.

I used the following to configure my Shelly devices:
```
shelly:
  discover_by_ip:
    - '172.16.x.x'
    - '172.16.x.y'
    - '172.16.x.z'
  devices:
    id: 'ABCDEF'
    light_switch: true
```

HA Version: `0.104.2`

Did I miss something to configure? I haven't tried to configure it with MQTT. 
I also opened the web interface of one of the Shelly devices and toggled the state in HA. The change has been reflected within ~1s in the web interface of the Shelly device. I assume, Shelly is registering the state fast enough. But how does HA gets informed about this? Polling?

Thank you.

**Comment by RenePhilipse** [comment]
Ik have the exact same issue. I just started with home automation, home assistent and Shelly and thought maybe i did something wrong. Switching from HA works fine, but state updating takes 30 tot 60 seconds.

**Comment by SBerg1980** [comment]
I have the same problem please update

**Comment by chemelli74** [comment]
Please check how your devices are discovered: mDNS ? CoAP ? IP ?

Simone

**Comment by RenePhilipse** [comment]
Mine are auto Discovery. In the properties is deze mdns.

**Comment by kasteleman** [comment]
How can I check how they are discovered?

Op za 15 feb. 2020 om 12:36 schreef RenePhilipse <notifications@github.com>

**Comment by chemelli74** [comment]
> Mine are auto Discovery. In the properties is deze mdns.

Istant update works only trough CoAP unfortunately.

Simone

**Comment by chemelli74** [comment]
> How can I check how they are discovered?
> 
> Op za 15 feb. 2020 om 12:36 schreef RenePhilipse <notifications@github.com>
> …

Please click on the shelly entity and check attributes; discovery should be one of those.

Simone

**Comment by RenePhilipse** [comment]
> > Mine are auto Discovery. In the properties is deze mdns.
> 
> Istant update works only trough CoAP unfortunately.
> 
> Simone

Thanks for the info. How can i switch tot this coap?? I cannot find this clearly in the documentation. Sorry.

**Comment by hakana** [comment]
It will use CoAP as default but some router/AP not supporting it. It uses UDP broadcast messages, look if you have a setting for IGMP in your router that you can enable.

**Comment by paolograssi** [comment]
How can we test if CoAP works in our network? I have the same issue.

Devices are discovered with CoAP but then goes in polling

**Comment by hakana** [comment]
It is to type of CoAP messages. One used for discovery and one for sending status messages. For you the discovery is working but not the status messages.

**Comment by paolograssi** [comment]
Wireshark shall detect it? Looking the list I assume I am not the only one. What is the best troubleshooting approach?

**Comment by chemelli74** [comment]
Yup, wireshark will, detect all network traffic. Be aware that you need to run it on HASS to be sure it is received or on the router itself to be sure it get generated.

Simone

**Comment by emnik** [comment]
same here... Used to work though.
I don't know what might caused it to stop as I did change so many things :-(
router (the new one is a TP-Link Archer C3150)
homeassistant update to the latest
shelly update to the latest...
So following here (CoAP discovery works,  first command is instant but status is has a long delay)
I tried all options for IGMP both in router and in shelly config but no change...

**Comment by emnik** [comment]
enabling the logger in HA I get the following:
When I click to turn on/off:
```
2020-02-17 09:40:54 DEBUG (SyncWorker_18) [pyShelly] http://192.168.0.84/relay/0?turn=on
2020-02-17 09:40:54 DEBUG (SyncWorker_18) [pyShelly] http://192.168.0.84/relay/0?turn=on - Ok
2020-02-17 09:40:59 DEBUG (Poll) [pyShelly] Sending CoAP discover UDP
2020-02-17 09:40:59 DEBUG (CoAP) [pyShelly] CoAP msg: 192.168.0.........
```
* it receives a CoAP message from every Shelly
Then it starts Polling every Shelly:
``` 2020-02-17 09:41:10 DEBUG (Poll) [pyShelly] Polling block, .... ```
When it'll get a response from all the Shellies (including the one I triggered) the state will be updated!
This happens on every click on every shelly. Is this the normal behavior?
I am using 0.1.6 with the latest HA Core.

**Comment by RenePhilipse** [comment]
Today I restarted my HA for some other changes and it logs the following errors at startup. Since I saw the word "COAP" in this, I thought it might be connected to this issue. I am using the ShellyForHass plugin version 0.1.6 and HA version 0.105.3.

`2020-02-17 09:37:43 ERROR (Poll) [pyShelly] Error update loop, [Errno 1] Operation not permitted, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 232, in _update_loop
    self.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 134, in discover
    self._coap.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 34, in discover
    self._socket.sendto(msg, (COAP_IP, COAP_PORT))
PermissionError: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 232, in _update_loop
    self.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 134, in discover
    self._coap.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 34, in discover
    self._socket.sendto(msg, (COAP_IP, COAP_PORT))
PermissionError: [Errno 1] Operation not permitted`

**Comment by palinf** [comment]
Isn't this issue a duplicate to https://github.com/StyraHem/ShellyForHASS/issues/158 ?

**Comment by emnik** [comment]
Yes it is...

Στις Τετ, 19 Φεβ 2020, 11:21 ο χρήστης palinf <notifications@github.com>
έγραψε:

**Comment by palinf** [comment]
I have the same issue with hassio docker installation. 
I am not very aware of CoAP protocol but I suppose it is related with some network problem. Since by adding the CoAP shelly discovery is fine (by adding `host_ip:` )
I would suppose that the CoAP clients (shellies) cannot access the CoAP server (ShellyForHASS) to update the status due to some forwarding rules not implemented through docker (probably same case for router)
Is there any port / way of doing, ShellyForHASS is advertising I should redirect ?

**Comment by chemelli74** [comment]
let's pn

> Isn't this issue a duplicate to #158 ?

Let's continue there.
Thank you for noticing.

Simone
