### ISSUE TITLE
[BUG] Shelly 2.5/1PM configured as light Load cause duplicate entity switch & light

### ISSUE THREAD

**Issue by HawkUser** [StyraHem/ShellyForHASS#462]
## Environment

- ShellyForHASS release with the issue: 0.2.0
- Last working ShellyForHASS release (if known): N/A
- Home Assistant Core release with the issue: 0.116.4
- Operating environment (Home Assistant/Supervised/Docker/venv): HassOS 4.14 (Supervised)

## Describe the bug
I have a few shelly devices that are configured as Light load type instead of the socket option (attached print screen), those devices represented in the HA as switch and light, while the switch entity seems to be "not responding", also, these devices are represented as not responding in homekit

## Steps to Reproduce
Configure shelly device as Light load type.

## Expected behavior
No duplicate should exist, only a light entity or switch.

## Screenshots
![image](https://user-images.githubusercontent.com/39925630/96407965-376fe980-11eb-11eb-9e00-183463dc3f47.png)
![image](https://user-images.githubusercontent.com/39925630/96408024-50789a80-11eb-11eb-8200-b115fa43bb44.png)

## Traceback/Error logs

```txt

```

**Comment by filmgarage** [comment]
This is actually a 'feature' in Home Assistant. As you can see from the icon to the right the switch entity is offline. HA will keep these old entities so it will be able to reconnect if it was to come back online. This is very helpful if you integrate the entities in HomeKit or otherwise. The very simple suolution to get rid of old entities is to delete them in HA. Just highlight all entities you want to remove and a dialog will come up asking what you want to do with them. Choose to delete old entities. BTW you cannot delete entities if they are still present in your setup!

**Comment by hakana** [comment]
Yes, that is like it should. I will close this issue now.
