### ISSUE TITLE
[BUG] Shelly 1L switch status not updating on 0.2.2.beta 1

### ISSUE THREAD

**Issue by theCheek** [StyraHem/ShellyForHASS#515]
## Environment

- ShellyForHASS release with the issue: 0.2.2.beta 1
- Last working ShellyForHASS release (if known): n/a 
- Home Assistant Core release with the issue:  2021.1.2
- Operating environment (Home Assistant/Supervised/Docker/venv): Docker

## Describe the bug

After updating to ShellyForHass 0.2.2 beta 1 (installed to enable Shelly 1L support) the binary_sensor.shelly1l_switch is not updating on state change. Also the attribute 'switch' in the switch.shelly1L is not updating, nor is shelly_switch_click event firing.

## Steps to Reproduce

Turn the physical switch of Shelly 1L. Notice that the state of the corresponding switch changes in the Shelly Web Interface, but no change occurs in HA's switch entities. 

## Expected behavior

binary_sensor.shelly1l_switch should change to on/off when physical switch is pressed
attribute 'switch' of switch.shelly1l should change to true/false when physical switch is pressed

## Screenshots

![Screenshot 2021-01-17 075716](https://user-images.githubusercontent.com/3003042/104832430-ae278c00-5899-11eb-8165-c1932c6ba1ac.png)
![Screenshot 2021-01-17 075651](https://user-images.githubusercontent.com/3003042/104832431-aec02280-5899-11eb-8396-cbcffa622c97.png)
![Screenshot 2021-01-17 075558](https://user-images.githubusercontent.com/3003042/104832432-af58b900-5899-11eb-84cd-cacbffa65e75.png)

## Traceback/Error logs

```txt

```

**Comment by kongo09** [comment]
The status of the switch connected to the relay is updating instantly for me, regardless whether I press the physical button attached to the device, the button on the web interface or the light switch in HA. They are all in sync and the lag is not more than a few ms.

What I did notice is that the switch state does not necessarily the relay state. That's understandable, as I use the edge switch setting in the Shelly, so the physical button (and attribute state) could be on while the light is off. It confused me first, but thinking about it, it is expected behaviour.

What is missing is a sensor for the second detached switch of the 1L. The corresponding sensor setting is enabled:

![image](https://user-images.githubusercontent.com/640121/105851060-d83c2500-5fe2-11eb-9ce8-901c776c044d.png)

**Comment by theCheek** [comment]
@kongo09 I eventually came to this same conclusion as I didn't realise there were two switch inputs on the 1L. As soon as I tapped "swap inputs" in the Shelly web interface, HA state changes worked perfectly. So clearly the second switch hasn't been mapped.

**Comment by kongo09** [comment]
@theCheek I have filed a separate bug #518  for the issue with the second switch 

@hakana I guess this bug can be closed then
