### ISSUE TITLE
MQTT is not working correctly with Shelly Dimmer 2

### ISSUE THREAD

**Issue by whig0** [StyraHem/ShellyForHASS#534]
## Environment

- ShellyForHASS release with the issue: 0.2.2 beta 3
- Last working ShellyForHASS release (if known): unknown
- Home Assistant Core release with the issue: core-2021.3.3
- Operating environment (Home Assistant/Supervised/Docker/venv): Hass.io on Raspberry 3

## Describe the bug

Added Shelly Dimmer 2 to ShellyForHASS via MQTT, using the supervised Mosquitto Broker.
When turning the light on or off there is no "command=on" published on the MQTT topic of the device.

## Steps to Reproduce

Turn light on or off and check with MQTT explorer

## Expected behavior

"on" should be published at "shellies/shellydimmer2-xx/light/0/command"

## Screenshots

![image](https://user-images.githubusercontent.com/12801636/111744844-20adeb80-888c-11eb-99f4-284d7a1783c6.png)

## Traceback/Error logs

```txt

```

**Comment by whig0** [comment]
Thanks for your fast fix on/off is now working fine but unfortunately the status isn’t reflected in home assistant instantly. As soon as I toggle the light on, home assistant sets it status back to off. After a few seconds it turns on again without any interaction.

**Comment by IQS-Leopold** [comment]
t@whig0 : This problem usually happens if your network has a problem with multicasting. This app uses CoAP/CoIoT to get the state back. But in some networks like ASUS AI-Meshs this is not working. The app also uses polling to ge the state but without the direct feedback after your action you get that effect.

I would prefer a slightly different approach than currently implemented:

The app should keep the state set by the user until it recognize the different either by CoAP or Polling. So the state would be correct in 99%. The case that the action hasn't performed and so the user setted state has to be reverted is in my opinion much rare in a good working network than the opposite.

**Comment by whig0** [comment]
> This app uses CoAP/CoIoT to get the state back.
Is CoAP used even when the Shellies are discovered via MQTT?

Currently I have two entities for the same Shelly. One via CoAP, one via MQTT (with custom MQTT prefix). The status of the CoAP entity changes instantly when turned on via a physical switch. The status of the MQTT changes after ~10 seconds.

**Comment by hakana** [comment]
@IQS-Leopold The status should change to user-set until next received update

@whig0  I'm not sure if I understand. If you use MQTT with ShellyForHass you should not change to a customized MQTT prefix because then it will not work. Yes, CoAP runs in parallel with MQTT.

**Comment by IQS-Leopold** [comment]
@hakana 
Thema this isnt Wirkung properly and we should open, an extra Bug. Behavior at my Setup:

User set light on. 
State is on.
State goes off.
State goes in after some seconds.

So it seems there ist a problem causing a state flip.

**Comment by whig0** [comment]
@hakana The strange thing is that this is working fine with my Shelly 1 and Shelly 1l. Only the Shelly Dimmer 2 have this problem. Maybe the MQTT status is not read on the correct MQTT topic as it is different. ('light' instead of 'relay')
