### ISSUE TITLE
Shelly rollers shutters missing

### ISSUE THREAD

**Issue by Raphael99-99** [StyraHem/ShellyForHASS#87]
HI
I got Home assistant. Installed HACS and then Shellyfor Hass, but in UI Lovelace it discovers only one roller shutter instead of three and discover surprisingly 4 switches, that I don’t own.
Is it my mistake? Can I do something for discover all the three rollers shutters?
Thanks

**Comment by bbartje** [comment]
It sees the other two shelly 2,5 as seperate switches. (Each shelly 2.5 is actually two switches)

Verstuurd vanaf mijn iPhone

Op 26 okt. 2019 om 11:05 heeft Raphael99-99 <notifications@github.com> het volgende geschreven:

﻿

HI
I got Home assistant. Installed HACS and then Shellyfor Hass, but in UI Lovelace it discovers only one roller shutter instead of three and discover surprisingly 4 switches, that I don’t own.
Is it my mistake? Can I do something for discover all the three rollers shutters?
Thanks

**Comment by Raphael99-99** [comment]
That's ok. Thanks
